AllCops:
  Exclude:
    - '*.gemspec'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 110
  Exclude:
    - 'spec/**/*'
      
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

