sudo: false
language: ruby
rvm:
  - 2.5.1
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: 247ZARRKlVJb77qEQbzDNNIrFkVMfzWR2VvXu3Bgc/GjvreYkSmYxHgWRiq1RLlDNU8ug58/WFq4ZkIs5SolvlGO3jiD5NPrNRIW3T7WmGUEtOY7102nmlKlrLTttJloH61aeEamIfjMEvwl5y1gtBB2jxGmygYEfJ61J+gu3TInpYYpOI6AKM6DHC6lwvhsozixKAMBclKsmg3EOr/HQvVbgr1FPDzwNhZUQWQ6oXQF58PM7Rm19iwliiXFeCjM8y4V+ljO1RHUTrcMQ+h77Qy+vp9WJUxpqGsexS54QZHsQ59xw51F0Hap8Xq0vX6TmGrLFLZgfWutmI9JVNSk0/WOumMxiu4MMVPuvvgd0jj7sl7TjjHfkcFPzXUxsn4M2X8ILAm/yMCdS5fF0A94AcL8oICTYup7vmb0NgwgpRgLu6uzlOWmHDAytmdPtcExFmkD0KH9g+/Pv3aJf+qWRAIipCJlYcWrBAD7mBwbIM4mlE8HRYbS4TwgXBmtdH4BrZh1+73TnaBFD7DzzDVAFFza0uI3rafrB6MxccWdRya9KmbGUxK0kGnK24zXdVmC4pr7LJ4t8zldp87siq4p99vTNJw+amw7Yk/7a4MzwIWbmBE0lj1Qklq8pkiOf1oOt7J1zlum1TkhAOwqt4vhoXYcpka9fGU6uURlN/6iKco=
  gem: browserslist_useragent
  on:
    tags: true
    repo: browserslist/browserslist-useragent-ruby
